name: OIDC Info

on:
  workflow_dispatch:

jobs:
  show-ids:
    name: Show GitHub Repository IDs
    runs-on: ubuntu-latest

    steps:
      - name: Display immutable GitHub IDs
        run: |
          echo "OWNER_ID=${{ github.repository_owner_id }}"
          echo "REPOSITORY_ID=${{ github.repository_id }}"